CREATE TABLE notification_preferences (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    like_review BOOLEAN NOT NULL DEFAULT TRUE,
    like_comment BOOLEAN NOT NULL DEFAULT TRUE,
    new_comment BOOLEAN NOT NULL DEFAULT TRUE,
    new_follow BOOLEAN NOT NULL DEFAULT TRUE,
    system BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
