package storage

import (
	"context"
	"fmt"
	"io"
	"strings"

	"github.com/minio/minio-go/v7"
	"github.com/minio/minio-go/v7/pkg/credentials"
)

type MinioStorage struct {
	client    *minio.Client
	bucket    string
	publicURL string
}

func NewMinioStorage(endpoint, accessKey, secretKey, bucket string, useSSL bool, publicURL string) (*MinioStorage, error) {
	client, err := minio.New(endpoint, &minio.Options{
		Creds:  credentials.NewStaticV4(accessKey, secretKey, ""),
		Secure: useSSL,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create minio client: %w", err)
	}

	return &MinioStorage{
		client:    client,
		bucket:    bucket,
		publicURL: publicURL,
	}, nil
}

func (s *MinioStorage) Upload(ctx context.Context, objectName string, reader io.Reader, size int64, contentType string) (string, error) {
	_, err := s.client.PutObject(ctx, s.bucket, objectName, reader, size, minio.PutObjectOptions{
		ContentType: contentType,
	})
	if err != nil {
		return "", fmt.Errorf("failed to upload object: %w", err)
	}

	url := fmt.Sprintf("%s/%s/%s", s.publicURL, s.bucket, objectName)
	return url, nil
}

func (s *MinioStorage) Delete(ctx context.Context, objectName string) error {
	err := s.client.RemoveObject(ctx, s.bucket, objectName, minio.RemoveObjectOptions{})
	if err != nil {
		return fmt.Errorf("failed to delete object: %w", err)
	}
	return nil
}

// DeleteByURL extracts the object name from a URL generated by Upload and deletes it.
// This is the inverse of the URL generation in Upload, keeping the mapping in one place.
func (s *MinioStorage) DeleteByURL(ctx context.Context, fileURL string) error {
	prefix := fmt.Sprintf("%s/%s/", s.publicURL, s.bucket)
	if !strings.HasPrefix(fileURL, prefix) {
		return fmt.Errorf("URL does not match storage prefix: %s", fileURL)
	}
	objectName := strings.TrimPrefix(fileURL, prefix)
	if objectName == "" {
		return fmt.Errorf("empty object name from URL: %s", fileURL)
	}
	return s.Delete(ctx, objectName)
}
